export const tournamentsMap: { [key: number]: string } = {
  1: 'UEFA EURO', // (masculino) (Europa)
  7: 'UEFA Champions League', // (Europa)
  8: 'LaLiga EA Sports', // 1a División (España)
  16: 'FIFA World Cup', // (masculino) (Internacional)
  17: 'Premier League', // 1a División (Inglaterra)
  19: 'Football Association Cup', // FA Cup (Inglaterra)
  21: 'English Football League Cup', // EFL Cup (Inglaterra)
  23: 'Lega Serie A', // 1a División (Italia)
  35: 'Bundesliga', // 1a División (Alemania)
  34: "Ligue 1 McDonald's", // 1a División (Francia)
  54: 'LaLiga Hypermotion', // 2a División (España)
  133: 'Conmebol Copa América', // (masculino) (Sudamérica)
  213: 'Supercopa de España', // (España)
  290: "FIFA Women's World Cup", // (femenino) (Internacional)
  329: 'Copa de S.M el Rey', // Copa del Rey (España)
  357: 'FIFA Club World Cup', // (Internacional)
  384: 'Copa Conmebol Libertadores', // (Sudamérica)
  436: 'Olimpiadas', // (masculino) (Internacional)
  437: 'Olimpiadas', // (femenino) (Internacional)
  465: 'UEFA Super Cup', // (Europa)
  477: "UEFA Women's EURO", // (femenino) (Europa)
  679: 'Europa League', // (Europa)
  17015: 'Conference League', // (Europa)
  10783: 'Nations League', // (masculino) (Europa)
};
